# Generated by Django 6.0.6 on 2026-06-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='remind_before_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='remind_enabled',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='remind_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
