# Generated by Django 6.0.6 on 2026-07-25 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_passwordresettoken_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PasswordResetToken',
            new_name='Password_reset_tokens',
        ),
    ]
