# Generated by Django 6.0.6 on 2026-06-20 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='parent_task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.tasks'),
        ),
    ]
