# Generated by Django 6.0.6 on 2026-06-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasks_parent_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='is_temp_subtask',
            field=models.BooleanField(default=False),
        ),
    ]
