# Generated by Django 6.0.6 on 2026-07-03 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_users_id_alter_users_table'),
        ('tasks', '0004_tasks_is_temp_subtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'condition_categories',
            },
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='tasks.condition_categories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='accounts.users')),
            ],
            options={
                'db_table': 'conditions',
            },
        ),
        migrations.CreateModel(
            name='Task_conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_conditions', to='tasks.conditions')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_conditions', to='tasks.tasks')),
            ],
            options={
                'db_table': 'task_conditions',
            },
        ),
    ]
