# Generated by Django 6.0.6 on 2026-07-06 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_users_id_alter_users_table'),
        ('tasks', '0005_condition_categories_conditions_task_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition_sets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('set_type', models.IntegerField(default=0)),
                ('use_count', models.IntegerField(default=0)),
                ('last_use_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_sets', to='accounts.users')),
            ],
            options={
                'db_table': 'condition_sets',
            },
        ),
        migrations.CreateModel(
            name='Condition_set_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_set_items', to='tasks.conditions')),
                ('condition_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_set_items', to='tasks.condition_sets')),
            ],
            options={
                'db_table': 'condition_set_items',
            },
        ),
    ]
